#include "DataFormats/Common/interface/Wrapper.h"
#include "DataFormats/FTLRecHitSoA/interface/BTLUncalibRecHitHostCollection.h"
#include "DataFormats/FTLRecHitSoA/interface/BTLUncalibRecHitSoA.h"
#include "DataFormats/FTLRecHitSoA/interface/BTLRecHitHostCollection.h"
#include "DataFormats/FTLRecHitSoA/interface/BTLRecHitSoA.h"
